  # Challenge

  ## Identifying Outliers using Standard Deviation

In [19]:
# initial imports
import pandas as pd
import numpy as np
import random
import hvplot.pandas
from sqlalchemy import create_engine

In [20]:
# create a connection to the database
engine = create_engine("postgresql://postgres:postgres@localhost:5432/SQL_hw_Fraud_detect")

rand1=random.randint(1,25)
rand2=random.randint(1,25)
rand3=random.randint(1,25)



query= f'''SELECT tr.date, tr.amount, tr.card, m.name, mc.name, credit_card.card_holder
FROM transactions AS tr
JOIN merchant AS m 
ON tr.merchant_id=m.id
JOIN merchant_catagory AS mc 
ON m.id_merchant_catagory=mc.id
JOIN credit_card on tr.card like 
CONCAT(SUBSTRING(CAST(CAST(credit_card.card AS BIGINT) AS VARCHAR(100)),1,4),'%%')
WHERE credit_card.card_holder={rand1} OR credit_card.card_holder={rand2} OR credit_card.card_holder={rand3}
'''

transactions_df = pd.read_sql(query, engine, index_col='date', parse_dates=True)
transactions_df.columns=['amount','card_num', 'merchant', 'category', 'holder']

transactions_df.head()

,amount,card_num,merchant,category,holder
date,,,,,
2018-01-02 04:36:45,3.36,4506405265172173,Martinez-Robinson,bar,20
2018-01-03 05:13:19,2.76,3535651398328201,Clark and Sons,food truck,20
2018-01-04 11:15:55,5.72,3535651398328201,"Bond, Lewis and Rangel",restaurant,20
2018-01-04 14:38:12,2.84,3535651398328201,Colon Ltd,bar,20
2018-01-04 19:24:31,14.31,4586962917519654607,"Jenkins, Peterson and Beck",restaurant,20

In [21]:
# code a function to identify outliers based on standard deviation
''' Outliers or non-normal data can be determined by a z-test 3.5<=|Yi-Yave|/s but NIST also recomments 3.5<=0.6745|Yi-Yave|/MAD
https://www.itl.nist.gov/div898/handbook/eda/section3/eda35h.htm'''

def std_outlier(df_group, holder):
    df=df_group.loc[df_group['holder']==holder]
    std=df['amount'].std()
    ave=df['amount'].mean()
    mask_std=abs(df['amount']-ave)/std>=3.5
    outlier_std=df.loc[mask_std]
    return outlier_std

def mad_outlier(df_group, holder):
    df=df_group.loc[df_group['holder']==holder]
    mad=df['amount'].mad()
    ave=df['amount'].mean()
    mask_mad=abs(.6745*(df['amount'])-ave)/mad>=3.5
    outlier_mad=df.loc[mask_mad]
    return outlier_mad

def iqr_outliers(df_group, holder):
    df=df_group.loc[df_group['holder']==holder]
    qtr1=df['amount'].quantile(.25)
    qtr3=df['amount'].quantile(.75)
    iqr15=1.5*(qtr1+qtr3)/2
    mask_iqr=(df['amount']<(qtr1-iqr15))|(df['amount']>(qtr3+iqr15))
    outlier_iqr=df.loc[mask_iqr]
    return outlier_iqr

In [22]:
# find anomalous transactions for 3 random card holders

In [23]:
holder1=transactions_df.loc[transactions_df['holder']==rand1]
holder1.hvplot.hist(y='amount', bins=10, alpha=0.5, height=400).opts(title=f'Histogram of transactions for card holder {rand1}')

:Histogram   [amount]   (amount_count)

In [24]:
outlier_std=std_outlier(transactions_df, rand1)
outlier_std

Empty DataFrame
Columns: [amount, card_num, merchant, category, holder]
Index: []

In [25]:
outlier_mad=mad_outlier(transactions_df, rand1)
outlier_mad

Empty DataFrame
Columns: [amount, card_num, merchant, category, holder]
Index: []

In [26]:
outlier_iqr=iqr_outliers(transactions_df, rand1)
outlier_iqr

,amount,card_num,merchant,category,holder
date,,,,,
2018-08-26 07:15:18,23.13,4506405265172173,Marshall-Lopez,food truck,20

In [27]:
holder2=transactions_df.loc[transactions_df['holder']==rand1]
holder2.hvplot.hist(y='amount', bins=10, alpha=0.5, height=400).opts(title=f'Histogram of transactions for card holder {rand2}')

:Histogram   [amount]   (amount_count)

In [28]:
outlier_std2=std_outlier(transactions_df, rand2)
outlier_std2

Empty DataFrame
Columns: [amount, card_num, merchant, category, holder]
Index: []

In [29]:
outlier_mad2=mad_outlier(transactions_df, rand2)
outlier_mad2

Empty DataFrame
Columns: [amount, card_num, merchant, category, holder]
Index: []

In [30]:
outlier_iqr2=iqr_outliers(transactions_df, rand2)
outlier_iqr2

,amount,card_num,merchant,category,holder
date,,,,,
2018-08-26 07:15:18,23.13,4506405265172173,Marshall-Lopez,food truck,20

In [31]:
holder3=transactions_df.loc[transactions_df['holder']==rand3]
holder3.hvplot.hist(y='amount', bins=10, alpha=0.5, height=400).opts(title=f'Histogram of transactions for card holder {rand3}')

:Histogram   [amount]   (amount_count)

In [32]:
outlier_std3=std_outlier(transactions_df, rand3)
outlier_std3

,amount,card_num,merchant,category,holder
date,,,,,
2018-04-21 19:41:51,2108.0,3581345943543942,"Brown, Estrada and Powers",coffee shop,6
2018-09-02 06:17:00,2001.0,3581345943543942,Romero-Jordan,food truck,6
2018-09-11 15:16:47,1856.0,3581345943543942,Mccullough-Murphy,food truck,6

In [33]:
outlier_mad3=mad_outlier(transactions_df, rand3)
outlier_mad3

,amount,card_num,merchant,category,holder
date,,,,,
2018-04-21 19:41:51,2108.0,3581345943543942,"Brown, Estrada and Powers",coffee shop,6
2018-07-03 14:56:36,1398.0,3581345943543942,Russell-Thomas,restaurant,6
2018-08-05 01:06:38,1379.0,3581345943543942,Hood-Phillips,bar,6
2018-09-02 06:17:00,2001.0,3581345943543942,Romero-Jordan,food truck,6
2018-09-11 15:16:47,1856.0,3581345943543942,Mccullough-Murphy,food truck,6
2018-11-27 17:20:29,1279.0,3581345943543942,"Jenkins, Peterson and Beck",restaurant,6

In [34]:
outlier_iqr3=iqr_outliers(transactions_df, rand3)
outlier_iqr3

,amount,card_num,merchant,category,holder
date,,,,,
2018-01-08 02:34:32,1029.0,3581345943543942,Hood-Phillips,bar,6
2018-02-27 15:27:32,1145.0,3581345943543942,Vasquez-Parker,bar,6
2018-03-09 04:51:38,389.0,3581345943543942,Lowe PLC,restaurant,6
2018-04-21 19:41:51,2108.0,3581345943543942,"Brown, Estrada and Powers",coffee shop,6
2018-07-03 14:56:36,1398.0,3581345943543942,Russell-Thomas,restaurant,6
2018-07-24 22:42:00,1108.0,3581345943543942,Jarvis-Turner,pub,6
2018-08-05 01:06:38,1379.0,3581345943543942,Hood-Phillips,bar,6
2018-09-02 06:17:00,2001.0,3581345943543942,Romero-Jordan,food truck,6
2018-09-11 15:16:47,1856.0,3581345943543942,Mccullough-Murphy,food truck,6
2018-11-27 17:20:29,1279.0,3581345943543942,"Jenkins, Peterson and Beck",restaurant,6

  ## Identifying Outliers Using Interquartile Range

In [35]:
# code a function to identify outliers based on interquartile range

In [36]:
# find anomalous transactions for 3 random card holders